name: Cross-compilation

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    name: Build for ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux_x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - os-name: Linux_aarch64
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-gnu
          - os-name: Windows_x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-gnu
          - os-name: Windows_x86
            runs-on: windows-latest
            target: i686-pc-windows-msvc
          - os-name: Windows_aarch64
            runs-on: windows-latest
            target: aarch64-pc-windows-msvc
          - os-name: macOS_x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin
          - os-name: macOS_aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract version number
        shell: bash
        run: echo "VERSION=$(grep -m 1 '^version' Cargo.toml | cut -d '"' -f 2)" >> $GITHUB_ENV
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      # Having all the files we want to include in the artifact in one folder means that everything can go in the root of the .zip
      - name: Copy README and LICENSE files
        shell: bash
        run: cp README.md LICENSE target/${{ matrix.platform.target }}/release/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Paint_2D_v${{ env.VERSION }}_${{ matrix.platform.os-name }}
          # Include paint-2d or paint-2d.exe, but not paint-2d.d
          path: |
            ./target/${{ matrix.platform.target }}/release/paint-2d*
            !**/*.d
            ./target/${{ matrix.platform.target }}/release/README.md
            ./target/${{ matrix.platform.target }}/release/LICENCE
          if-no-files-found: error
